apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: delivery-system

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-user.yaml
  - postgres-order.yaml
  - postgres-payment.yaml
  - rabbitmq.yaml
  - user-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - notification-service.yaml
  - api-gateway.yaml
  - frontend.yaml
  - nginx.yaml

