apiVersion: v1
kind: Service
metadata:
  name: db-order
  namespace: delivery-system
spec:
  selector:
    app: db-order
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-order
  namespace: delivery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-order
  template:
    metadata:
      labels:
        app: db-order
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: order_service_db
            - name: POSTGRES_USER
              value: delivery_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
          ports:
            - containerPort: 5432


