apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: delivery-system
type: Opaque
stringData:
  user-db-url: "postgresql://delivery_user:YourStrongPassword123@db-user:5432/user_service_db"
  order-db-url: "postgresql://delivery_user:YourStrongPassword123@db-order:5432/order_service_db"
  payment-db-url: "postgresql://delivery_user:YourStrongPassword123@db-payment:5432/payment_service_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: delivery-system
type: Opaque
stringData:
  jwt-secret: "supersecretkey123"
  chapa-secret-key: "CHASECK_TEST-tN76XXA4XXBORpqJEWk1Jw56t7Jy7KXT"

